import { Inter } from "next/font/google";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "EcoVista",
    description: "Generated by create Hasan U Khan",
};

export default function RootLayout({ children, aqi, temperature, weather }) {
    return (
        <div className="wrapper">
            {children}
            {aqi}
            {temperature}
            {weather}
        </div>
    );
}
